openapi: 3.0.0
info:
  description: |
    This is the hot item status microservice that polls data from an excel file.
  version: "1.0.0"
  title: Status Microservice
  contact:
    email: terry.chan@hohokusinc.com
    
tags:
  - name: status
    description: Everything about status

paths:
  /status:
    get:
      tags:
        - status
      summary: Get all status at Paterson
      operationId: getStatusnj
      parameters:
        - name: sorting
          in: query
          description: This is getting the suggestion status with sorting order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/statusInfo'
        '404':
          description: Item not found

components:
  schemas:
    statusInfo:
      type: object
      properties:
        part_number:
          type: string
          example: 5H8000K-08
        job_number:
          type: string
          example: 5H9700-5Z
        quantity:
          type: string
          example: 50min
        last_updated:
          type: string
          example: 7/16/2020 16:38
        comments:
          type: string
          example: Need heat treat
        due_date:
          type: string
          example: ASAP